from datos.info_version import numero_version
from datos.info_app import titulo_app,opcion_invalida,correo_invalido,telefono_invalido,contrasena_invalida,correo_usado
from datos.info_menus import menu_aplicacion,sub_menu
from datos.info_rifas import listado_rifas
from datos.info_usuarios import listado_usuarios
from datos.datos_usuarios import guardar_usuario
from datos.conexion import guardar_datos