INSERT INTO tipos_usuario(tipo_usuario,descripcion_tipo_usuario)
VALUES
('Administrador','Genera y administra rifas y usuarios'),
('Revisor','Puede ver la información de rifas.');

INSERT INTO nacionalidades (pais, iso2, iso3, nacionalidad, codigo) VALUES
('Afganistán', 'AF', 'AFG', 'Afgana', '93'),
('Albania', 'AL', 'ALB', 'Albanesa', '355'),
('Alemania', 'DE', 'DEU', 'Alemana', '49'),
('Andorra', 'AD', 'AND', 'Andorrana', '376'),
('Angola', 'AO', 'AGO', 'Angoleña', '244'),
('Antigua y Barbuda', 'AG', 'ATG', 'Antiguana', '1268'),
('Arabia Saudita', 'SA', 'SAU', 'Saudí', '966'),
('Argelia', 'DZ', 'DZA', 'Argelina', '213'),
('Argentina', 'AR', 'ARG', 'Argentina', '54'),
('Armenia', 'AM', 'ARM', 'Armenia', '374'),
('Australia', 'AU', 'AUS', 'Australiana', '61'),
('Austria', 'AT', 'AUT', 'Austriaca', '43'),
('Azerbaiyán', 'AZ', 'AZE', 'Azerbaiyana', '994'),
('Bahamas', 'BS', 'BHS', 'Bahameña', '1242'),
('Bangladés', 'BD', 'BGD', 'Bangladesí', '880'),
('Barbados', 'BB', 'BRB', 'Barbadense', '1246'),
('Baréin', 'BH', 'BHR', 'Bareiní', '973'),
('Bélgica', 'BE', 'BEL', 'Belga', '32'),
('Belice', 'BZ', 'BLZ', 'Beliceña', '501'),
('Benín', 'BJ', 'BEN', 'Beninesa', '229'),
('Bielorrusia', 'BY', 'BLR', 'Bielorrusa', '375'),
('Birmania', 'MM', 'MMR', 'Birmana', '95'),
('Bolivia', 'BO', 'BOL', 'Boliviana', '591'),
('Bosnia y Herzegovina', 'BA', 'BIH', 'Bosnia', '387'),
('Botsuana', 'BW', 'BWA', 'Botsuana', '267'),
('Brasil', 'BR', 'BRA', 'Brasileña', '55'),
('Brunéi', 'BN', 'BRN', 'Bruneana', '673'),
('Bulgaria', 'BG', 'BGR', 'Búlgara', '359'),
('Burkina Faso', 'BF', 'BFA', 'Burkinesa', '226'),
('Burundi', 'BI', 'BDI', 'Burundesa', '257'),
('Bután', 'BT', 'BTN', 'Butanesa', '975'),
('Cabo Verde', 'CV', 'CPV', 'Caboverdiana', '238'),
('Camboya', 'KH', 'KHM', 'Camboyana', '855'),
('Camerún', 'CM', 'CMR', 'Camerunesa', '237'),
('Canadá', 'CA', 'CAN', 'Canadiense', '1'),
('Catar', 'QA', 'QAT', 'Catarí', '974'),
('Chad', 'TD', 'TCD', 'Chadina', '235'),
('Chile', 'CL', 'CHL', 'Chilena', '56'),
('China', 'CN', 'CHN', 'China', '86'),
('Chipre', 'CY', 'CYP', 'Chipriota', '357'),
('Colombia', 'CO', 'COL', 'Colombiana', '57'),
('Comoras', 'KM', 'COM', 'Comorense', '269'),
('Corea del Norte', 'KP', 'PRK', 'Norcoreana', '850'),
('Corea del Sur', 'KR', 'KOR', 'Surcoreana', '82'),
('Costa de Marfil', 'CI', 'CIV', 'Marfileña', '225'),
('Costa Rica', 'CR', 'CRI', 'Costarricense', '506'),
('Croacia', 'HR', 'HRV', 'Croata', '385'),
('Cuba', 'CU', 'CUB', 'Cubana', '53'),
('Dinamarca', 'DK', 'DNK', 'Danesa', '45'),
('Dominica', 'DM', 'DMA', 'Dominiquesa', '1767'),
('Ecuador', 'EC', 'ECU', 'Ecuatoriana', '593'),
('Egipto', 'EG', 'EGY', 'Egipcia', '20'),
('El Salvador', 'SV', 'SLV', 'Salvadoreña', '503'),
('Emiratos Árabes Unidos', 'AE', 'ARE', 'Emiratí', '971'),
('Eritrea', 'ER', 'ERI', 'Eritrea', '291'),
('Eslovaquia', 'SK', 'SVK', 'Eslovaca', '421'),
('Eslovenia', 'SI', 'SVN', 'Eslovena', '386'),
('España', 'ES', 'ESP', 'Española', '34'),
('Estados Unidos', 'US', 'USA', 'Estadounidense', '1'),
('Estonia', 'EE', 'EST', 'Estonia', '372'),
('Etiopía', 'ET', 'ETH', 'Etíope', '251'),
('Filipinas', 'PH', 'PHL', 'Filipina', '63'),
('Finlandia', 'FI', 'FIN', 'Finlandesa', '358'),
('Fiyi', 'FJ', 'FJI', 'Fiyiana', '679'),
('Francia', 'FR', 'FRA', 'Francesa', '33'),
('Gabón', 'GA', 'GAB', 'Gabonesa', '241'),
('Gambia', 'GM', 'GMB', 'Gambiana', '220'),
('Georgia', 'GE', 'GEO', 'Georgiana', '995'),
('Ghana', 'GH', 'GHA', 'Ghanesa', '233'),
('Granada', 'GD', 'GRD', 'Granadina', '1473'),
('Grecia', 'GR', 'GRC', 'Griega', '30'),
('Guatemala', 'GT', 'GTM', 'Guatemalteca', '502'),
('Guyana', 'GY', 'GUY', 'Guyanesa', '592'),
('Guinea', 'GN', 'GIN', 'Guineana', '224'),
('Guinea-Bisáu', 'GW', 'GNB', 'Bisauguineana', '245'),
('Guinea Ecuatorial', 'GQ', 'GNQ', 'Ecuatoguineana', '240'),
('Haití', 'HT', 'HTI', 'Haitiana', '509'),
('Honduras', 'HN', 'HND', 'Hondureña', '504'),
('Hungría', 'HU', 'HUN', 'Húngara', '36'),
('India', 'IN', 'IND', 'India', '91'),
('Indonesia', 'ID', 'IDN', 'Indonesia', '62'),
('Irak', 'IQ', 'IRQ', 'Iraquí', '964'),
('Irán', 'IR', 'IRN', 'Iraní', '98'),
('Irlanda', 'IE', 'IRL', 'Irlandesa', '353'),
('Islandia', 'IS', 'ISL', 'Islandesa', '354'),
('Islas Marshall', 'MH', 'MHL', 'Marshalesa', '692'),
('Islas Salomón', 'SB', 'SLB', 'Salomonense', '677'),
('Israel', 'IL', 'ISR', 'Israelí', '972'),
('Italia', 'IT', 'ITA', 'Italiana', '39'),
('Jamaica', 'JM', 'JAM', 'Jamaiquina', '1876'),
('Japón', 'JP', 'JPN', 'Japonesa', '81'),
('Jordania', 'JO', 'JOR', 'Jordana', '962'),
('Kazajistán', 'KZ', 'KAZ', 'Kazaja', '7'),
('Kenia', 'KE', 'KEN', 'Keniata', '254'),
('Kirguistán', 'KG', 'KGZ', 'Kirguisa', '996'),
('Kiribati', 'KI', 'KIR', 'Kiribatiana', '686'),
('Kuwait', 'KW', 'KWT', 'Kuwaití', '965'),
('Laos', 'LA', 'LAO', 'Laosiana', '856'),
('Lesoto', 'LS', 'LSO', 'Lesotense', '266'),
('Letonia', 'LV', 'LVA', 'Letona', '371'),
('Líbano', 'LB', 'LBN', 'Libanesa', '961'),
('Liberia', 'LR', 'LBR', 'Liberiana', '231'),
('Libia', 'LY', 'LBY', 'Libia', '218'),
('Liechtenstein', 'LI', 'LIE', 'Liechtensteiniana', '423'),
('Lituania', 'LT', 'LTU', 'Lituana', '370'),
('Luxemburgo', 'LU', 'LUX', 'Luxemburguesa', '352'),
('Macedonia del Norte', 'MK', 'MKD', 'Macedonia', '389'),
('Madagascar', 'MG', 'MDG', 'Malgache', '261'),
('Malasia', 'MY', 'MYS', 'Malaya', '60'),
('Malaui', 'MW', 'MWI', 'Malauí', '265'),
('Maldivas', 'MV', 'MDV', 'Maldivana', '960'),
('Malí', 'ML', 'MLI', 'Maliense', '223'),
('Malta', 'MT', 'MLT', 'Maltesa', '356'),
('Marruecos', 'MA', 'MAR', 'Marroquí', '212'),
('Mauricio', 'MU', 'MUS', 'Mauriciana', '230'),
('Mauritania', 'MR', 'MRT', 'Mauritana', '222'),
('México', 'MX', 'MEX', 'Mexicana', '52'),
('Micronesia', 'FM', 'FSM', 'Micronesia', '691'),
('Moldavia', 'MD', 'MDA', 'Moldava', '373'),
('Mónaco', 'MC', 'MCO', 'Monegasca', '377'),
('Mongolia', 'MN', 'MNG', 'Mongola', '976'),
('Montenegro', 'ME', 'MNE', 'Montenegrina', '382'),
('Mozambique', 'MZ', 'MOZ', 'Mozambiqueña', '258'),
('Namibia', 'NA', 'NAM', 'Namibia', '264'),
('Nauru', 'NR', 'NRU', 'Nauruana', '674'),
('Nepal', 'NP', 'NPL', 'Nepalí', '977'),
('Nicaragua', 'NI', 'NIC', 'Nicaragüense', '505'),
('Níger', 'NE', 'NER', 'Nigerina', '227'),
('Nigeria', 'NG', 'NGA', 'Nigeriana', '234'),
('Noruega', 'NO', 'NOR', 'Noruega', '47'),
('Nueva Zelanda', 'NZ', 'NZL', 'Neozelandesa', '64'),
('Omán', 'OM', 'OMN', 'Omaní', '968'),
('Países Bajos', 'NL', 'NLD', 'Neerlandesa', '31'),
('Pakistán', 'PK', 'PAK', 'Pakistaní', '92'),
('Palaos', 'PW', 'PLW', 'Palauana', '680'),
('Panamá', 'PA', 'PAN', 'Panameña', '507'),
('Papúa Nueva Guinea', 'PG', 'PNG', 'Papú', '675'),
('Paraguay', 'PY', 'PRY', 'Paraguaya', '595'),
('Perú', 'PE', 'PER', 'Peruana', '51'),
('Polonia', 'PL', 'POL', 'Polaca', '48'),
('Portugal', 'PT', 'PRT', 'Portuguesa', '351'),
('Reino Unido', 'GB', 'GBR', 'Británica', '44'),
('República Centroafricana', 'CF', 'CAF', 'Centroafricana', '236'),
('República Checa', 'CZ', 'CZE', 'Checa', '420'),
('República del Congo', 'CG', 'COG', 'Congoleña', '242'),
('República Democrática del Congo', 'CD', 'COD', 'Congoleña', '243'),
('República Dominicana', 'DO', 'DOM', 'Dominicana', '1809'),
('Ruanda', 'RW', 'RWA', 'Ruandesa', '250'),
('Rumanía', 'RO', 'ROU', 'Rumana', '40'),
('Rusia', 'RU', 'RUS', 'Rusa', '7'),
('Samoa', 'WS', 'WSM', 'Samoana', '685'),
('San Cristóbal y Nieves', 'KN', 'KNA', 'Cristobaleña', '1869'),
('San Marino', 'SM', 'SMR', 'Sanmarinense', '378'),
('San Vicente y las Granadinas', 'VC', 'VCT', 'Sanvicentina', '1784'),
('Santa Lucía', 'LC', 'LCA', 'Santalucense', '1758'),
('Santo Tomé y Príncipe', 'ST', 'STP', 'Santotomense', '239'),
('Senegal', 'SN', 'SEN', 'Senegalesa', '221'),
('Serbia', 'RS', 'SRB', 'Serbia', '381'),
('Seychelles', 'SC', 'SYC', 'Seychellense', '248'),
('Sierra Leona', 'SL', 'SLE', 'Sierraleonesa', '232'),
('Singapur', 'SG', 'SGP', 'Singapurense', '65'),
('Siria', 'SY', 'SYR', 'Siria', '963'),
('Somalia', 'SO', 'SOM', 'Somalí', '252'),
('Sri Lanka', 'LK', 'LKA', 'Ceilanesa', '94'),
('Suazilandia', 'SZ', 'SWZ', 'Suazi', '268'),
('Sudáfrica', 'ZA', 'ZAF', 'Sudafricana', '27'),
('Sudán', 'SD', 'SDN', 'Sudanesa', '249'),
('Sudán del Sur', 'SS', 'SSD', 'Sursudanesa', '211'),
('Suecia', 'SE', 'SWE', 'Sueca', '46'),
('Suiza', 'CH', 'CHE', 'Suiza', '41'),
('Surinam', 'SR', 'SUR', 'Surinamesa', '597'),
('Tailandia', 'TH', 'THA', 'Tailandesa', '66'),
('Taiwán', 'TW', 'TWN', 'Taiwanesa', '886'),
('Tanzania', 'TZ', 'TZA', 'Tanzana', '255'),
('Tayikistán', 'TJ', 'TJK', 'Tayika', '992'),
('Timor Oriental', 'TL', 'TLS', 'Timorense', '670'),
('Togo', 'TG', 'TGO', 'Togolesa', '228'),
('Tonga', 'TO', 'TON', 'Tongana', '676'),
('Trinidad y Tobago', 'TT', 'TTO', 'Trinitense', '1868'),
('Túnez', 'TN', 'TUN', 'Tunecina', '216'),
('Turkmenistán', 'TM', 'TKM', 'Turcomana', '993'),
('Turquía', 'TR', 'TUR', 'Turca', '90'),
('Tuvalu', 'TV', 'TUV', 'Tuvaluana', '688'),
('Ucrania', 'UA', 'UKR', 'Ucraniana', '380'),
('Uganda', 'UG', 'UGA', 'Ugandesa', '256'),
('Uruguay', 'UY', 'URY', 'Uruguaya', '598'),
('Uzbekistán', 'UZ', 'UZB', 'Uzbeka', '998'),
('Vanuatu', 'VU', 'VUT', 'Vanuatuense', '678'),
('Venezuela', 'VE', 'VEN', 'Venezolana', '58'),
('Vietnam', 'VN', 'VNM', 'Vietnamita', '84'),
('Yemen', 'YE', 'YEM', 'Yemení', '967'),
('Yibuti', 'DJ', 'DJI', 'Yibutiana', '253'),
('Zambia', 'ZM', 'ZMB', 'Zambiana', '260'),
('Zimbabue', 'ZW', 'ZWE', 'Zimbabuense', '263');